[main]
sync_dir_path = "/home/user/sync/dir/path"

[api]
api_url = "https://api.yandex.net/v1"
oauth_url = "https://oauth.yandex.ru"
client_id = "47dc6152c0274ceab34dbf2e873bed50"

[meta_db]
path = ".cache/yad/meta.db"
